### ISSUE TITLE
论文参数细节

### ISSUE THREAD

**Issue by Nikol-coder** [NJUNLP/MORE#1]
您好，通过多次复现您的论文，感觉复现出来的结果跟原论文结果还是有一定的差距，想向您请教一下实验过程中所使用的超参数？
![image](https://github.com/user-attachments/assets/f8595348-0d30-4300-a488-1d1ace3bfb28)
![image](https://github.com/user-attachments/assets/80b21ca6-03e2-4710-a893-771ab82f2053)

**Comment by njucs** [comment]
你好！

我们应该已经在论文和代码里说明了超参数设置，如果有不清楚的可以再发邮件询问。
也可以参考我们的checkpoint（同步更新在GitHub）：
https://pan.baidu.com/s/1ILc61-HOn1eKWb-rsep4Ig?pwd=hjch

Sent with a Spark
在 2024年8月19日 +0800 15:43，林昕奎 ***@***.***>，写道：

**Comment by Nikol-coder** [comment]
好的，非常感谢，那我再多试一试！
